---
title: "Reading log"
author: "Last update at: `r format(Sys.time(), '%Y-%m-%d')`"

output: 
  html_notebook:
    theme: readable
    css: style.css  
    code_folding: "none"
    toc: true
    toc_float: true

---

```{r echo=FALSE}
source("functions.R")
```

```{css echo=FALSE}
.btn-group{
  display:none;
}
.title {
  color: white;
}
h1{
  color: white;
  text-align: left;
  font-family: Georgia;
  font-size: 30pt
}
h2{
  color: white;
  font-weight: bold;
  font-family: Georgia;
}

```

[Back to overview](./Overview.nb.html)

- To read (updated at `r format(Sys.time(), '%Y-%m-%d')`): 
  - Van Haeringen, E. S., Gerritsen, C., & Hindriks, K. V. (2023). Emotion contagion in agent-based simulations of crowds: A systematic review. Autonomous Agents and Multi-Agent Systems, 37(1), 6. https://doi.org/10.1007/s10458-022-09589-z
  - Van Haeringen, E., Gerritsen, C., & Hindriks, K. (2021). Integrating Valence and Arousal Within an Agent-Based Model of Emotion Contagion. In F. Dignum, J. M. Corchado, & F. De La Prieta (Eds.), Advances in Practical Applications of Agents, Multi-Agent Systems, and Social Good. The PAAMS Collection (Vol. 12946, pp. 303–315). Springer International Publishing. https://doi.org/10.1007/978-3-030-85739-4_25
    - Cited by Goldenberg 2023 on collective emotion 
  - Guilbeault, D., & Centola, D. (2021). Topological measures for identifying and predicting the spread of complex contagions. Nature Communications, 12(1), 4430. https://doi.org/10.1038/s41467-021-24704-6
    - Cited by the emotion regulation contagion paper 
  - Wojcieszak, M., Casas, A., Yu, X., Nagler, J., & Tucker, J. A. (2022). Most users do not follow political elites on Twitter; those who do show overwhelming preferences for ideological congruity. Science Advances, 8(39), eabn9418. https://doi.org/10.1126/sciadv.abn9418
  - Huth, K. B. S., Haslbeck, J. M. B., Keetelaar, S., Van Holst, R. J., & Marsman, M. (2025). Statistical evidence in psychological networks. Nature Human Behaviour. https://doi.org/10.1038/s41562-025-02314-2
  - Argyle, L. P., Busby, E. C., Gubler, J. R., Lyman, A., Olcott, J., Pond, J., & Wingate, D. (2025). Testing theories of political persuasion using AI. Proceedings of the National Academy of Sciences, 122(18), e2412815122. https://doi.org/10.1073/pnas.2412815122
  - Salvi, F., Horta Ribeiro, M., Gallotti, R., & West, R. (2025). On the conversational persuasiveness of GPT-4. Nature Human Behaviour, 1–9. https://doi.org/10.1038/s41562-025-02194-6



# 2025-11-18
- Brady, W. J., Crockett, M. J., & Van Bavel, J. J. (2020). The MAD model of moral contagion: The role of motivation, attention, and design in the spread of moralized content online. Perspectives on Psychological Science, 15(4), 978–1010. https://doi.org/10.1177/1745691620917336 [[link]](./Brady_etal_2020/Brady_etal_2020.nb.html)
- Vlasceanu, M., Dyckovsky, A. M., & Coman, A. (2023). A Network Approach to Investigate the Dynamics of Individual and Collective Beliefs: Advances and Applications of the BENDING Model. Perspectives on Psychological Science, 17456916231185776. https://doi.org/10.1177/17456916231185776
  - Participant-by-item matrix can be used to construct community-level belief networks based on what items people agree on 
- Goldenberg, A., Garcia, D., Halperin, E., & Gross, J. J. (2020). Collective emotions. Current Directions in Psychological Science, 29(2), 154–160. [[link]](./Goldenberg_etal_2020/Goldenberg_etal_2020.nb.html)


# 2025-11-17
- Goldenberg, A. (2023). What makes groups emotional? Perspectives on Psychological Science. https://doi.org/10.1177/17456916231179154 [[link]](./Goldenberg_2023/Goldenberg_2023.nb.html)
  - Propose the interaction-cognition-infrastructure framework to understand collective emotions, specifically why emotions get amplified 
- Handbook of emotion regulation -- chapters on collective emotion regulation, emotion regulation in conflict resolution 
- Psychological Intergroup Intervention -- chapter on emotion regulation in conflict resolution 
  - Indirect emotion regulation intervention -- targeting other things that may change emotions, instead of directly targeting emotions with emotion regulation strategies 
- Porat, R., Halperin, E., & Tamir, M. (2016). What we want is what we get: Group-based emotional preferences and conflict resolution. Journal of Personality and Social Psychology, 110(2), 167–190. https://doi.org/10.1037/pspa0000043
  - Rightist show more preference for anger, leftist show more preference for empathy 
  - Emotion preference is associated with emotional experiences which in turn is associated emotion intergroup repsonses (e.g., support for conclitoary policies)
  - Changing emotion prefernece changes emotoinal experience and therefore intergroup responses
  - Mostly focused on anger; empathy was only measured in the pilot study 
- Pinus, M., Cao, Y., Halperin, E., Coman, A., Gross, J. J., & Goldenberg, A. (2025). Emotion regulation contagion drives reduction in negative intergroup emotions. Nature Communications, 16(1), 1387. https://doi.org/10.1038/s41467-025-56538-x
  - Vector of "pure reappraisal"
  - Simulation to handle drop-outs 


- 2025-06-19
  - Lorenz-Spreen, P., Oswald, L., Lewandowsky, S., & Hertwig, R. (2022). A systematic review of worldwide causal and correlational evidence on digital media and democracy. Nature Human Behaviour, 7(1), 74–101. https://doi.org/10.1038/s41562-022-01460-1
    - Digital media is associated with decreased trust in government in established democracies, but not in emerging democracies
  - Skeggs, A., & Orben, A. (2025). Social media interventions to improve well-being. Nature Human Behaviour, 1–11. https://doi.org/10.1038/s41562-025-02167-9
    - Use the Self-determination theory framework to evaluate the effectiveness of social media interventions
  - Wulff, D. U., & Mata, R. (2025). Semantic embeddings reveal and address taxonomic incommensurability in psychological measurement. Nature Human Behaviour, 9(5), 944–954. https://doi.org/10.1038/s41562-024-02089-y

- 2025-06-16
  - Stella, M., Ferrara, E., & De Domenico, M. (2018). Bots increase exposure to negative and inflammatory content in online social systems. Proceedings of the National Academy of Sciences, 115(49), 12435–12440. https://doi.org/10.1073/pnas.1803470115
  - Tsvetkova, M., Yasseri, T., Pescetelli, N., & Werner, T. (2024). A new sociology of humans and machines. Nature Human Behaviour, 8(10), 1864–1876. https://doi.org/10.1038/s41562-024-02001-8
    - A complex system view of human-human, human-machine, and machine-machine interactions
  - Ashery, A. F., Aiello, L. M., & Baronchelli, A. (2025). Emergent social conventions and collective bias in LLM populations. Science Advances, 11(20), eadu9368. https://doi.org/10.1126/sciadv.adu9368
    - LLM agents can develop a consensus through interactions; 
    - different models have different preferences for the final consensus decision
    - test the "critical mass" threshold for changing the consensus from minority 
  - Schroeder, D., Cha, M., Baronchelli, A., Bostrom, N., Christakis, N., Garcia, D., Goldenberg, A., Kyrychenko, Y., Leyton-Brown, K., Lutz, N., Marcus, G., Menczer, F., Pennycook, G., Rand, D., Schweitzer, F., Summerfield, C., Tang, A., Van Bavel, J., Linden, S. van der, … Kunst, J. (2025). How Malicious AI Swarms Can Threaten Democracy. OSF. https://doi.org/10.31219/osf.io/qm9yk_v1
    - See figure 1 for the key framework and conceptualization

- 2024-06-25
  - Mooijman, M., Hoover, J., Lin, Y., Ji, H., & Dehghani, M. (2018). Moralization in social networks and the emergence of violence during protests. Nature Human Behaviour, 2(6), Article 6. https://doi.org/10.1038/s41562-018-0353-0
  - D’Amore, C., van Zomeren, M., & Koudenburg, N. (2022). Attitude moralization within polarized contexts: An emotional value-protective response to dyadic harm cues. Personality and Social Psychology Bulletin, 48(11), 1566–1579. https://doi.org/10.1177/01461672211047375
  - Vollberg, M. C., & Cikara, M. (2024). Affective prediction errors in persistence and escalation of aggression. Journal of Experimental Psychology: General, 153(6), 1551–1567. https://doi.org/10.1037/xge0001570
  - Fung, H. H. (2024). Aging in culture revisited. Current Opinion in Psychology, 56, 101777. https://doi.org/10.1016/j.copsyc.2023.101777
  - Jost, J. T., Baldassarri, D. S., & Druckman, J. N. (2022). Cognitive–motivational mechanisms of political polarization in social-communicative contexts. Nature Reviews Psychology, 1(10), 560–576. https://doi.org/10.1038/s44159-022-00093-5


- 2024-06-20
  - Firth, J., Torous, J., López-Gil, J. F., Linardon, J., Milton, A., Lambert, J., Smith, L., Jarić, I., Fabian, H., Vancampfort, D., Onyeaka, H., Schuch, F. B., & Firth, J. A. (2024). From “online brains” to “online lives”: Understanding the individualized impacts of Internet use across psychological, cognitive and social dimensions. World Psychiatry, 23(2), 176–190. https://doi.org/10.1002/wps.21188
  - Connolly, P.-S., Hull, T. D., & Bonanno, G. A. (2019). A regulatory flexibility perspective on positive emotion. In J. Gruber (Ed.), The Oxford Handbook of Positive Emotion and Psychopathology (pp. 50–63). Oxford University Press. https://books.google.com/books?hl=en&lr=&id=lvarDwAAQBAJ&oi=fnd&pg=PA50&dq=info:eXPLeeqtWk0J:scholar.google.com&ots=Xn6lW7p6sx&sig=ruD5w_zGcgMV2YGHHwuq1KBkwLo 
  - Carlson, R. W., Bigman, Y. E., Gray, K., Ferguson, M. J., & Crockett, M. J. (2022). How inferred motives shape moral judgements. Nature Reviews Psychology, 1(8), 468–478. https://doi.org/10.1038/s44159-022-00071-x


- 2024-06-19
  - Wang, S.-Y. N., & Inbar, Y. (2021). Moral-language use by U.S. political elites. Psychological Science, 32(1), 14–26. https://doi.org/10.1177/0956797620960397
  - Fan, L., Molho, C., Kupfer, T. R., Sauter, D. A., & Tybur, J. M. (2024). Beyond outrage: Observers anticipate different behaviors from expressors of anger versus disgust. Social Psychological and Personality Science, 15(4), 450–460. https://doi.org/10.1177/19485506231176954



- 2024-02-14 
  - Romero, D. M., Uzzi, B., & Kleinberg, J. (2019). Social Networks under Stress: Specialized Team Roles and Their Communication Structure. ACM Transactions on the Web, 13(1), 1–24. https://doi.org/10.1145/3295460
    - How external events (shocks) affect the network structure, including individual- and firm-level cognition and behavior 
      - Turtle up ---> instead of relying on weak ties, they cluster together 
  - Turner-Zwinkels, F. M., van Noord, J., Kesberg, R., García-Sánchez, E., Brandt, M. J., Kuppens, T., Easterbrook, M. J., Smets, L., Gorska, P., Marchlewska, M., & Turner-Zwinkels, T. (2023). Affective Polarization and Political Belief Systems: The Role of Political Identity and the Content and Structure of Political Beliefs. Personality and Social Psychology Bulletin, 01461672231183935. https://doi.org/10.1177/01461672231183935
    - The differential effects of beliefs content and structure similarity 
      - Their similairty measures are uncommon (absolute difference score and correlation)

- 2024-02-13 
  - Goldenberg, A., & Gross, J. J. (2020). Digital Emotion Contagion. Trends in Cognitive Sciences, 24(4), 316–328. https://doi.org/10.1016/j.tics.2020.01.009
    - Has interesting references on social movements in the digital world 
    - It presents evidence that (1) positivity is more prevalent than negativity, (2) positivity is shared more than negativity 
  - Wadley, G., Smith, W., Koval, P., & Gross, J. J. (2020). Digital Emotion Regulation. Current Directions in Psychological Science, 29(4), 412–418. https://doi.org/10.1177/0963721420920592


- 2024-01-19
  - Boker Segal, N., Hu, D., Ginosar Yaari, S., & Tamir, M. (2024). Knowing me, knowing you: Are people good at regulating their emotions good at regulating another’s emotions? Emotion. https://doi.org/10.1037/emo0001305
    - Self-oriented emotion regulation ability is not correlated with other-oriented emotion regulation ability 
    - The extent to which the receiver's emotion is down regulated is correlated to their own emotion regulation ability 
 

- 2024-01-18 
  - Finkel, E. J., Bail, C. A., Cikara, M., Ditto, P. H., Iyengar, S., Klar, S., Mason, L., McGrath, M. C., Nyhan, B., Rand, D. G., Skitka, L. J., Tucker, J. A., Van Bavel, J. J., Wang, C. S., & Druckman, J. N. (2020). Political sectarianism in America. Science, 370(6516), 533–536. https://doi.org/10.1126/science.abe1715
    - Three ingredients of sectarianism: othering, aversion, moralization 
  - Yeomans, M., Boland, F. K., Collins, H. K., Abi-Esber, N., & Brooks, A. W. (2023). A Practical Guide to Conversation Research: How to Study What People Say to Each Other. Advances in Methods and Practices in Psychological Science, 6(4), 25152459231183919. https://doi.org/10.1177/25152459231183919
    - There's mention of a R package for clustering standard error (estimatr: https://declaredesign.org/r/estimatr/)

- 2024-01-05 
  - Bhargava, S. (2023). Experienced love: An empirical account. Psychological Science, 09567976231211267. https://doi.org/10.1177/09567976231211267
    - Love is not prevalent  
    - Love experience varies across age and racial categories 
    - Gender gap in the experiences of love 
  - Ashokkumar, A., & Pennebaker, J. W. (2022). Tracking group identity through natural language within groups. PNAS Nexus, 1(2), pgac022. https://doi.org/10.1093/pnasnexus/pgac022
    - Group identity strength index --- unquestioning affiliation index
      - Predicts self-reported group identity, college retention, group leaving 


- 2023-03-28
  - Yarrington, J. S., et al. (2023). `r colored(" [[Note](./Yarrington_etal_2023/Yarrington_etal_2023.nb.html)]","#8CC1DE" ,"14pt")`
The role of positive and negative aspects of life events in depressive and anxiety symptoms. Clinical Psychological Science, 21677026221141656. https://doi.org/10.1177/21677026221141654


- 2023-03-26
  - Shen, H., Labroo, A., & Wyer, R. S. Jr. (2020). `r colored(" [[Note](./Shen_etal_2020/Shen_etal_2020.nb.html)]","#8CC1DE" ,"14pt")`
So difficult to smile: Why unhappy people avoid enjoyable activities. Journal of Personality and Social Psychology, 119(1), 23–39. https://doi.org/10.1037/pspa0000186

- 2023-03-25 
  - Koutsoumpis, A., et al. (2022). `r colored(" [[Note](./Koutsoumpis_etal_2022/Koutsoumpis_etal_2022.nb.html)]","#8CC1DE" ,"14pt")` 

  The kernel of truth in text-based personality assessment: A meta-analysis of the relations between the Big Five and the Linguistic Inquiry and Word Count (LIWC). Psychological Bulletin, 148(11–12), 843–868. https://doi.org/10.1037/bul0000381
  
  - Ryan, R. M., et al (2022). `r colored(" [[Note](./Ryan_etal_2022/Ryan_etal_2022.nb.html)]","#8CC1DE" ,"14pt")`

  We Know This Much Is (Meta-Analytically) True: A Meta-Review of Meta-Analytic Findings Evaluating Self-Determination Theory. Psychological Bulletin, 148(11/12), 813–842. https://doi.org/10.1037/bul0000385

- 2022-12-28 
  - Subject: Finished [Kraus et al., 2013](/Users/yuchenwei/Desktop/Academy/Readings/Kraus_2013/Kraus_2013.nb.html)
  - Subject: Finished [Snibbe & Markus, 2005](/Users/yuchenwei/Desktop/Academy/Readings/Snibbe_2005/Snibbe_2005.nb.html) 
